<?php

/**
 * Implements hook_form_alter().
 */
function hopform_captcha_form_hopform_form_form_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'captcha', 'captcha.admin');
  module_load_include('inc', 'captcha', 'captcha');

  $current_captcha = '';
  if (!empty($form_state['hopform_form']->fid)) {
    $current_captcha = captcha_get_form_id_setting(HOPFORM_FORM_PREFIX . $form_state['hopform_form']->fid, TRUE);
  }

  if (empty($current_captcha) || $current_captcha == 'none' || $current_captcha == 'default') {
    $current_captcha = '';
  }

  $form['captcha_type'] = array(
    '#title' => t('What kind of captcha challenge would you like?'),
    '#type' => 'select',
    '#options' => _captcha_available_challenge_types(FALSE),
    '#empty_option' => t('No CAPTCHA'),
    '#empty_value' => '',
    '#default_value' => $current_captcha,
  );

  $form['#submit'][] = 'hopform_captcha_submit';
}

function hopform_captcha_submit(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'captcha', 'captcha');

  $value = !empty($form_state['values']['captcha_type']) ? $form_state['values']['captcha_type'] : NULL;
  captcha_set_form_id_setting(HOPFORM_FORM_PREFIX . $form_state['fid'], $value);
}
